language: node_js
node_js:
- '0.12'
install:
- npm install
- gem install sass
- npm install -g grunt-cli
- bower install
script: grunt --env=prod
deploy:
  provider: heroku
  on: heroku
  app: infrastructure
  skip_cleanup: true
  api_key:
    secure: ArEOl0hYTUCOhaelcPpiDGL7Z56obFjRI28tNfFqLBhJT4njvdlUBkyvUPiPUsM1KhvhCYwRxdLPa7SUnhqdPVxjKWNjuNmdw1QB8DJPiegxmt80hLFzWskPmada07T8aLbv6MDWzh/xPz44mimNMIp0xQQafSn0lf9EI3cmpa0oEOacFPdjn7m5xVBYQUsVcUo9V0hJnrfR2CEtLRFMKySeq83CWit7aaaLn6jrVwDj18+qFItiBSFfl
                6FeXwZzN7ZvUzq133goTNB5mVlSyGo1Ep2lIbpPWt3AuIU6IdXxxwD0exT10Nn0hevc94Is+zYOxgrTK/l4zcdSqOlBCz2vMsGSvwe4O3f1yzVC6voZjPU31j3FmRhvppyT1FNvOrvyC3Ns4cbBmDQzThNvaUEFNQoixzXd1yt4mfITUWfz6M0qCbhm8y5lQyIRBYeDypTFt/+oU240yQqDn2neej6ZWQi7Dk+T21y0sytNYq7kNGerHVCcWw+rF3M42
                Ttvxd+C5ukRld72ymGTYaZkbGN0iQ8gsEOUd6TpyjTJeiGyZend2ft6xOq/CstCxIBMJmVMXUWTXhi+pALJqVvWEREWngQd9r8baA39gj90dmlyplggeRaOgK/cSwPXRre6wbx6+6FT4vikhNy3x9EAouzXjiMUFSAH+l1bd8BBYQI=