language: node_js
node_js:
- '0.12'
install:
- npm install
- gem install sass
- npm install -g grunt-cli
- bower install
script: grunt --env=prod
deploy:
  provider: heroku
  on: heroku
  skip_cleanup: true
  api_key:
    secure: OjJM8KHa8LHuJVtkTLuqTb5zmgIX8Jv1PzcZXjqEij8VJtfrKNYCujxYWqbbb+URlO2binDPez/WwH1bNB3MZbZTl1/zChWCHO5A+4kFMdHSCUUtGzbiNX3FjDuTazN+WglY2u3LhC8E0UuODfHgk15AYTFCZCQdC1J7SgF/KNtIJXS8qgYcQk/92od9jBuWVNAbDuUHlKxCCXJlxQIUdbvTNGcVQ+M7SFqmLNSL7GHl9uu94pRcPhwCfQYMUCeZqj7Zj7RpBlkmL0qjfil9m4eKZ+5NjV6+GA7r9sHhNrAZ9e/fLkaSXsGlhn2Etx6z/QDwDH2RlBeT8Z+20o3cAbXaWld9z7lCeqVsyJMvKnLrgvuwvpLJSNAjSAqG3rIFIra+LQhLjb6/I3B7df1cgO64nk7BBKWUnUrWWOaRmuarrjyrsFLManeKbJg2+r7V6BGllc+mOr+hmlklzgYcrHJPCkI/qoot71jW7rDPESpJVgIHO1L2N+Fh8YwQOf/csnCTBGrApBF3sDgxQAoXUef+hU4lCROGyRgRjSLWSAkb0K2/ljFl9X+CHoDHNnQ26PSecwhKW2o9IBqghXH3T6RCvWVhg5ltm2o9NBEZ9EBNlKG0caomif71EcGYdKYUz4wPe15DgMrMx0Gv/KwFcsE6rUzNVCFWbxf+fMY4YUs=

