language: node_js
node_js:
- '0.12'
install:
- npm install
- gem install sass
- npm install -g grunt-cli
- bower install
script: grunt --env=prod
deploy:
  provider: heroku
  on: heroku
  skip_cleanup: true
  api_key:
    secure: d84ba99d-718e-4dd9-b839-1357efdb40cb