language: node_js
node_js:
- '0.12'
install:
  - npm install
  - gem install sass
  - npm install -g grunt-cli
  - bower install
script: grunt --env=prod
deploy:
  provider: heroku
  skip_cleanup: true
  on: heroku
  api_key:
    secure: pe+kXSaJS9Of5Z+kTxIzsj14jYY42JtlwrYVr6xoZNxOm+avmj9Ytw4HoPzAveD+tNDAEz3c1kCcHd94BqcZX5jYczpAgocZx2acEoU2s7pkBGrqzxxC7H0nsaAonHPQQxy8vXtdpgDwMkcTNPNBEuH2Qc6288pJifux8ttK3klhsHvjJe1kdrJlo8YRZZ9SbqWsjHfpUDslmD2vD4K4vaGAo5spwg5QGwaEoucrg4EUkDWZbIAz8/OFYBfdPNNLE51pGtX7CL3VWYdsEbJ6Q4mU1uf9oeQ6Qf/wI/EVIvnKnYL2tum3EZmNaZ8vOsmNqCNXtbP0RGIoXbhkcVKk0BybIk/ytHNf27w4jw/OUCAnYMl6XeSmtE/CmRSZqvmmh9iS9pKgpZ2JlxVa5v/WnnQmNsQnKabBr4PfNazMYeeR5uR9l0dJOuIJEjglv10Km6ML++mNGu/50Td+yA1NtHiiBqkI+15shU3GhMZ9uEtwEOEkSLUeJ5KtLlwTUpJ3q9s65BfqAelre9UzUVpievUDYafgXNYcWLoXfr0HgUtyp+W9tCcVu52XRTGFJ+FPErvtEIb1xB7kZq4VDsEyfl+t82xgtfvuuoyaYJqM48YeIwq1agCiLovOZpf0wR/ci4KIzFFwh2Zh7d0uYknw8RMh1rZJlh2SdVq2TIhwKdQ=
